-- TABELAS

CREATE TABLE CLIENTE
(
	CPF_CLIENTE VARCHAR(14) PRIMARY KEY,
	CEP_CLIENTE VARCHAR(9),
	TEL_CLIENTE VARCHAR(17),
	CREDITO_TEL_CLIENTE NUMERIC(5,2),
	NOME_CLIENTE VARCHAR(100),
	IDADE_CLIENTE INT NOT NULL,
	EMAIL_CLIENTE VARCHAR(200),
	SENHA_CLIENTE VARCHAR(200),
	NUMERO_QRCODE_CLIENTE INT,
	NUMERO_BOLETO_CLIENTE INT,
	CHAVE_ALEATORIA_CLIENTE INT
);

CREATE TABLE CONTA_CLIENTE
(
	CPF_CONTA_CLIENTE VARCHAR(14) PRIMARY KEY,
	NOME_CONTA_CLIENTE VARCHAR(100),
	TEL_CONTA_CLIENTE VARCHAR(17),
	EMAIL_CONTA_CLIENTE VARCHAR(200),
	SENHA_CONTA_CLIENTE VARCHAR(200),
	SALDO_CONTA_CLIENTE NUMERIC(5,2),
	NUMERO_BANCO_CONTA NUMERIC(3,0),
	NUMERO_AGENCIA_CONTA NUMERIC(4,0),
	NUMERO_CONTA_CLIENTE INT,
	DATA_CRIACAO_CONTA VARCHAR(200),
	CHAVE_ALEATORIA_CONTA_CLIENTE INT,
	NUMERO_QRCODE_CONTA_CLIENTE INT,
	NUMERO_BOLETO_CONTA_CLIENTE INT,
	CONSTRAINT FK_CPF_CONTA_CLIENTE_CLIENTE FOREIGN KEY			
	(CPF_CONTA_CLIENTE) REFERENCES CLIENTE (CPF_CLIENTE)		
);



CREATE TABLE TRANSACAO_VARCHAR
(
	ID_TRANSACAO INT PRIMARY KEY,
	CPF_TRANSFERENCIA VARCHAR(14),
	CHAVE_TRANSFERIDA VARCHAR(200),
	TIPO_TRANSACAO VARCHAR(200),
	VALOR_TRANSACAO NUMERIC(5,2),
	DATA_TRANSACAO VARCHAR(200)
);

CREATE TABLE TRANSACAO_INT
(
	ID_TRANSACAO INT PRIMARY KEY,
	CPF_TRANSFERENCIA VARCHAR(14),
	CHAVE_TRANSFERIDA INT,
	TIPO_TRANSACAO VARCHAR(200),
	VALOR_TRANSACAO NUMERIC(5,2),
	DATA_TRANSACAO VARCHAR(200)
);


CREATE TABLE INFO_CARTAO
(
	NOME_INFO_CARTAO VARCHAR(100),
	CPF_INFO_CARTAO VARCHAR(14) PRIMARY KEY,
	RUA_INFO_CARTAO VARCHAR(100),
	NUMERO_CASA_INFO_CARTAO INT,
	CEP_INFO_CARTAO VARCHAR(9),
	IDADE_INFO_CARTAO INT NOT NULL,
	CONSTRAINT FK_INFO_CARTAO_CONTA_CLIENTE FOREIGN KEY
	(CPF_INFO_CARTAO) REFERENCES CONTA_CLIENTE (CPF_CONTA_CLIENTE)
);

CREATE TABLE CARTAO_BANCO
(
	CPF_TITULAR_CARTAO VARCHAR(14) PRIMARY KEY,
	TITULAR_CARTAO VARCHAR(100),
	NUMERO_CARTAO INT,
	VALIDADE_CARTAO VARCHAR(20),
	CODIGO_SEGURANCA_CARTAO NUMERIC(3,0),
	CONSTRAINT FK_INFO_CARTAO_CONTA_CLIENTE FOREIGN KEY
	(CPF_TITULAR_CARTAO) REFERENCES CONTA_CLIENTE (CPF_CONTA_CLIENTE)
);

CREATE TABLE CADASTRO_BANCO
(
	CPF_BANCO VARCHAR(14) PRIMARY KEY,
	NUMERO_AGENCIA_BANCO NUMERIC(4,0),
	NUMERO_CONTA_BANCO VARCHAR(20),
	CVV_CONTA_BANCO NUMERIC (3,0),
	TIPO_CONTA_BANCO VARCHAR(200)
);




--- MOSTRAR AS INFORMACOES


SELECT * FROM CLIENTE;
SELECT * FROM CONTA_CLIENTE;
SELECT * FROM TRANSACAO_VARCHAR;
SELECT * FROM TRANSACAO_INT;
SELECT * FROM INFO_CARTAO;
SELECT * FROM CARTAO_BANCO;
SELECT * FROM CADASTRO_BANCO;


-- EXCLUIR AS TABELAS
DROP TABLE CLIENTE;
DROP TABLE CONTA_CLIENTE;
DROP TABLE TRANSACAO_VARCHAR;
DROP TABLE TRANSACAO_INT;
DROP TABLE INFO_CARTAO;
DROP TABLE CARTAO_BANCO;
DROP TABLE CADASTRO_BANCO;


